name: Silverstripe CMS CI Database step
description: Run PHPUnit test for a Siverstripe CMS module
inputs:
  driver:
    description: Which Database to use
    required: true
    default: mysql
  version:
    description: Which version to use
    required: false
# outputs:
#   SS_DATABASE_CLASS:
#     description: "Database class"
#     value: ${{ steps.cnx.outputs.SS_DATABASE_CLASS }}
#   SS_DATABASE_SERVER:
#     description: "Database server"
#     value: ${{ steps.cnx.outputs.SS_DATABASE_SERVER }}
#   SS_DATABASE_USERNAME:
#     description: "Database username"
#     value: ${{ steps.cnx.outputs.SS_DATABASE_USERNAME }}
#   SS_DATABASE_PASSWORD:
#     description: "Database password"
#     value: ${{ steps.cnx.outputs.SS_DATABASE_PASSWORD }}
#   SS_DATABASE_NAME:
#     description: "Database name"
#     value: ${{ steps.cnx.outputs.SS_DATABASE_NAME}}

runs:
  using: "composite"
  steps:
    - name: Kill local MySQL instance
      run: sudo service mysql stop
      shell: bash
      
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: ${{ inputs.version || 5.7 }}
        mysql root password: root

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password=root --silent; do
          sleep 1
        done
      shell: bash

    # - name: Return connection info
    #   id: cnx
    #   run: |
    #     echo "::set-output name=SS_DATABASE_CLASS::MySQLDatabase"
    #     echo "::set-output name=SS_DATABASE_USERNAME::root"
    #     echo "::set-output name=SS_DATABASE_PASSWORD::root"
    #     echo "::set-output name=SS_DATABASE_SERVER::127.0.0.1"
    #     echo "::set-output name=SS_DATABASE_NAME::SS_mysite"
    #   shell: bash

    - name: Export Connection settings
      run: |
        echo "SS_DATABASE_CLASS=MySQLDatabase" >> $GITHUB_ENV
        echo "SS_DATABASE_USERNAME=root" >> $GITHUB_ENV
        echo "SS_DATABASE_PASSWORD=monkey" >> $GITHUB_ENV
        echo "SS_DATABASE_SERVER=127.0.0.1" >> $GITHUB_ENV
        echo "SS_DATABASE_NAME=SS_mysite" >> $GITHUB_ENV
      shell: bash


#   SS_DATABASE_SERVER: 127.0.0.1
#   SS_DATABASE_USERNAME: root
#   SS_DATABASE_PASSWORD: root
#   SS_DATABASE_NAME: SS_mysite