name: Silverstripe CMS CI Database step
description: Run PHPUnit test for a Siverstripe CMS module
inputs:
  driver:
    description: Which Database to use
    required: true
    default: mysql
  version:
    description: Which version to use
    required: false
    default: latest

runs:
  using: "composite"
  steps:  
  
    # Catch all failure statement  
    - name: Validate DB driver
#      if: inputs.driver != 'mysql' && inputs.driver != 'mariadb' && inputs.driver != 'postgresql'
      if: contains(['mysql','mariadb','postgresql'],inputs.driver) === false
      uses: actions/github-script@v3
      with:
        script: core.setFailed('${{ inputs.driver }} is not a supported DB')

    
    - name: Kill local MySQL instance
      run: sudo service mysql stop
      shell: bash
      
      
    # MySQL/MariaDB set up  
    - name: Set up MySQL
      if: inputs.driver == 'mysql'
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: ${{ inputs.version }}
        mysql root password: root

    - name: Set up MariaDB
      if: inputs.driver == 'mariadb'
      uses: getong/mariadb-action@v1.1
      with:
        mariadb version: ${{ inputs.version || 'latest' }}
        mysql root password: root

    - name: Wait for MySQL/MariaDB
      if: inputs.driver == 'mysql' || inputs.driver == 'mariadb'
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password=root --silent; do
          sleep 1
        done
      shell: bash

    - name: Export Connection settings
      if: inputs.driver == 'mysql' || inputs.driver == 'mariadb'
      run: |
        echo "SS_DATABASE_CLASS=MySQLDatabase" >> $GITHUB_ENV
        echo "SS_DATABASE_USERNAME=root" >> $GITHUB_ENV
        echo "SS_DATABASE_PASSWORD=root" >> $GITHUB_ENV
        echo "SS_DATABASE_SERVER=127.0.0.1" >> $GITHUB_ENV
        echo "SS_DATABASE_NAME=SS_mysite" >> $GITHUB_ENV
      shell: bash
      
    # PostgreSQL set up
    - name: Set up PostgreSQL
      if: inputs.driver == 'postgresql'
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: ${{ inputs.version || 'latest' }}
        postgresql db: 'postgres'
        postgresql user: 'postgres'
    - name: Wait for PostgreSQL
      if: inputs.driver == 'postgresql'
      run: sleep 20
      shell: bash
    - name: Install PostgreSQL module
      if: inputs.driver == 'postgresql'
      run: composer require silverstripe/postgresql --quiet --no-update
      shell: bash
    - name: Export Connection settings
      if: inputs.driver == 'postgresql'
      run: |
        echo "SS_DATABASE_CLASS=PostgreSQLDatabase" >> $GITHUB_ENV
        echo "SS_DATABASE_USERNAME=postgres" >> $GITHUB_ENV
        echo "SS_DATABASE_PASSWORD=postgres" >> $GITHUB_ENV
        echo "SS_DATABASE_SERVER=127.0.0.1" >> $GITHUB_ENV
        echo "SS_DATABASE_NAME=SS_mysite" >> $GITHUB_ENV
      shell: bash
    
