name: Silverstripe CMS CI Database step
description: Run PHPUnit test for a Siverstripe CMS module
inputs:
  driver:
    description: Which Database to use
    required: true
    default: mysql
  version:
    description: Which version to use
    required: false

runs:
  using: "composite"
  steps:
    - name: Kill local MySQL instance
      run: sudo service mysql stop
      shell: bash
      
    - name: Set up MySQL
      if: inputs.driver == 'mysql'
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: ${{ inputs.version || 5.7 }}
        mysql root password: root

    - name: Set up MariaDB
      if: inputs.driver == 'mariadb'
      uses: getong/mariadb-action@v1.1
      with:
        mariadb version: ${{ inputs.version || 'latest' }}
        mysql root password: root

    - name: Wait for MySQL/MariaDB
      if: inputs.driver == 'mysql' || inputs.driver == 'mariadb'
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password=root --silent; do
          sleep 1
        done
      shell: bash

    - name: Export Connection settings
      if: inputs.driver == 'mysql' || inputs.driver == 'mariadb'
      run: |
        echo "SS_DATABASE_CLASS=MySQLDatabase" >> $GITHUB_ENV
        echo "SS_DATABASE_USERNAME=root" >> $GITHUB_ENV
        echo "SS_DATABASE_PASSWORD=root" >> $GITHUB_ENV
        echo "SS_DATABASE_SERVER=127.0.0.1" >> $GITHUB_ENV
        echo "SS_DATABASE_NAME=SS_mysite" >> $GITHUB_ENV
      shell: bash
