name: build-test

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: none
  discussions: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Basic MysQL and Maria DB connection
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        db:
          - driver: mysql
            expectedVersion: 5.7
          - driver: mysql
            version: 5.7
            expectedVersion: 5.7
          - driver: mariadb
            expectedVersion: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run actions
      uses: ./
      with:
        driver: ${{ matrix.db.driver }}
        version: ${{ matrix.db.version }}

    - name: Test connection
      run: |
        VERSION=`mysql -s -N \
          -h${{ env.SS_DATABASE_SERVER }} \
          -u${{ env.SS_DATABASE_USERNAME }} \
          -p${{ env.SS_DATABASE_PASSWORD }} \
          -e 'SELECT VERSION();' \
          ${{ env.SS_DATABASE_NAME }}`
        echo "VERSION='$VERSION'" >> $GITHUB_ENV
    
    - name: Validate DB version
      if: "!contains(env.VERSION, matrix.db.expectedVersion)"
      uses: actions/github-script@v3
      with:
        script: core.setFailed('${{ env.VERSION }} does not match expeced version ${{ matrix.db.expectedVersion }}')
          

  integration:
    name: Integration test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db:
          - driver: mysql
            version: 5
          - driver: mysql
            version: 8
          - driver: mariadb
          - driver: postgresql

    steps:
    
    - name: Clone test repo
      run: git clone --branch 1.2.0 https://github.com/silverstripe/silverstripe-config.git .
    
    - name: Checkout action
      uses: actions/checkout@v2
      with:
        path: myaction/

    - run: ls -la

    - name: Set up PHP
      uses: maxime-rainville/silverstripe-ci-setup@master
      with:
        composer-stability: --prefer-stable
        phpVersion: 7.4

    - name: Run actions
      uses: ./myaction
      with:
        driver: ${{ matrix.db.driver }}
        version: ${{ matrix.db.version }}

    - name: Run test suite
      uses: maxime-rainville/silverstripe-ci-phpunit@master