name: build-test

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: none
  discussions: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Basic MysQL and Maria DB connection
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        db:
          - mysql
          - mariadb

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run actions
      uses: ./
      with:
        driver: ${{ matrix.db }}

    - name: Test connection
      run: |
        mysqladmin ping \
          --host=${{ env.SS_DATABASE_SERVER }} \
          --user=${{ env.SS_DATABASE_USERNAME }} \
          --password=${{ env.SS_DATABASE_PASSWORD }}; \

  integration:
    name: Integration test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db:
          - driver: mysql
            version: 5
          - driver: mysql
            version: 8
          - driver: mariadb
          - driver: postgresql

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clone PHP lib
      run: git clone --depth 1 --branch 1.2.0 git@github.com:silverstripe/silverstripe-config.git

    - run: ls -la

    - name: Set up PHP
      uses: maxime-rainville/silverstripe-ci-setup@master
      working-directory: silverstripe-config
      with:
        composer-stability: --prefer-stable
        phpVersion: 7.4

    - name: Run actions
      uses: ./myaction
      working-directory: silverstripe-config
      with:
        driver: ${{ matrix.db.driver }}
        version: ${{ matrix.db.version }}

    - name: Run test suite
      working-directory: silverstripe-config
      uses: maxime-rainville/silverstripe-ci-phpunit@master