name: build-test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  basic connection:
  
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        db:
          - mysql
          - mariadb

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: List file
      run: ls -la

    - name: Run actions
      uses: ./
      with:
        db: ${{ input.db }}

    - name: Test result
      run: |
        mysqladmin ping \
          --host=${{ env.SS_DATABASE_SERVER }} \
          --user=${{ env.SS_DATABASE_USERNAME }} \
          --password=${{ env.SS_DATABASE_PASSWORD }}; \
