name: build-test

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: none
  discussions: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
  
    name: Basic MysQL and Maria DB connection
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        db:
          - mysql
          - mariadb

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run actions
      uses: ./
      with:
        db: ${{ matrix.db }}

    - name: Test result
      run: |
        mysqladmin ping \
          --host=${{ env.SS_DATABASE_SERVER }} \
          --user=${{ env.SS_DATABASE_USERNAME }} \
          --password=${{ env.SS_DATABASE_PASSWORD }}; \
